---
title: "Gov 50 Final Project"
author: "Jordy Chaves"
description: "My Final Project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to football/soccer statistics. Perhaps analyzing  the expected goals (xG) of Premier League teams or how different tactics and line-ups influence the distribution of ball possession across the field. 

## Data:

```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
Data <- read_csv("Data/spi_matches.csv")

Data <- Data |>
  drop_na()

pl_table_2016 <- Data |>
  filter(league == "Barclays Premier League", season == "2016") |>
  mutate(result = case_when(score1 > score2 ~ " Home Win",
                            score1 < score2 ~ "Away Win",
                            score2 == score1 ~ "Draw")) |>
  group_by(importance1, importance2)
pl_table_2016
  
pl_importance <- ggplot(data = pl_table_2016, mapping = aes(x = importance1)) +
    geom_histogram() +
    labs(x = "Degree of Importance of a Game to the Home Team", y = "Count")
pl_importance
```

## Proposal:


Does the importance of a soccer game influence whether or not a team wins a game? In this study, I plan to examine if a game is deemed more important for a team, will that team win that game. I hypothesize that teams will win a game when it is more important to them than it is to their opponent. My sample is comprised of the 20 English Premier League teams in the 2016 season. I will be using the spi.matches.csv dataset. My unit of analysis will be a team (e.g. Manchester United, Leicester City, etc.). The explanatory variable of interest is how important a game is to a team (importance1 for a home team and importance 2 for an away team). The explanatory variable is measured on a scale of 0-100, 0 meaning not important and 100 meaning the most important. My outcome variable would be a count of the number of wins each team has on a range of how important the games were (e.g., count of wins in games that range from 0-20 in importance, 20-40, 40-60, etc.). If I observe more wins when the importance of the game is higher, then this will provide support for my hypothesis. If I observe more wins when the game is of less importance to a team, then this will provide evidence against my hypothesis.